name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{secrets.GCP_KEY}}
      
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: 'latest'
        project_id: sp-dashboard-434500

    - name: Authenticate Docker to Artifact Registry
      run: |
        echo "Authenticating Docker to Artifact Registry..."
        gcloud auth configure-docker us-docker.pkg.dev
        echo "Docker authenticated successfully."

    - name: Build and push backend Docker image
      run: |
        echo "Building and pushing the backend Docker image..."
        docker buildx build --platform linux/amd64 -t us-docker.pkg.dev/sp-dashboard-434500/docker/sp-dashboard-backend:latest -f backend/Dockerfile .
        docker push us-docker.pkg.dev/sp-dashboard-434500/docker/sp-dashboard-backend:latest
        echo "Backend Docker image built and pushed successfully."

    - name: Build and push frontend Docker image
      run: |
        echo "Building and pushing the frontend Docker image..."
        docker buildx build --platform linux/amd64 -t us-docker.pkg.dev/sp-dashboard-434500/docker/sp-dashboard-frontend:latest -f src/Dockerfile .
        docker push us-docker.pkg.dev/sp-dashboard-434500/docker/sp-dashboard-frontend:latest
        echo "Frontend Docker image built and pushed successfully."

    - name: Deploy to Cloud Run Backend
      run: |
        echo "Deploying backend to Cloud Run..."
        gcloud run deploy sp-dashboard-backend \
          --image=us-docker.pkg.dev/sp-dashboard-434500/docker/sp-dashboard-backend:latest \
          --region=us-central1 \
          --platform=managed \
          --allow-unauthenticated \
          --set-env-vars "REACT_APP_BACKEND_URL=https://sp-dashboard-backend-77119817287.us-central1.run.app" \
          --set-env-vars "REACT_APP_FRONTEND_URL=https://sp-dashboard-frontend-77119817287.us-central1.run.app" 
        echo "Backend deployed to Cloud Run."

    - name: Deploy to Cloud Run Frontend
      run: |
        echo "Deploying frontend to Cloud Run..."
        gcloud run deploy sp-dashboard-frontend \
          --image=us-docker.pkg.dev/sp-dashboard-434500/docker/sp-dashboard-frontend:latest \
          --region=us-central1 \
          --platform=managed \
          --allow-unauthenticated \
          --set-env-vars "REACT_APP_BACKEND_URL=https://sp-dashboard-backend-77119817287.us-central1.run.app" \
          --set-env-vars "REACT_APP_FRONTEND_URL=https://sp-dashboard-frontend-77119817287.us-central1.run.app" 
        echo "Frontend deployed to Cloud Run."
